### PR TITLE
Js first

### PR DESCRIPTION
**Pull request by NedealcovaIrina**

### CODE REVIEW

**Comment by NedealcovaIrina** [comment]
I've added a lot of files and photos, don't pay attention to it yet. Please check only what is related to the js homework)

**Review by MItan9 — APPROVED** [review]
I checked only js file and it is well done

**Review by IvanCebanPVT — APPROVED** [review]
Well done!

**Review by IvanCeban — APPROVED** [review]

**Comment by IvanCeban** [comment]
please merge your approved PRs. 
It gets pretty difficult to check your new PR that includes all previous.

**Pull request merged**
